# Generated by Django 5.1.3 on 2024-12-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='tg_auth_token',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='telegram_auth_token'),
        ),
    ]
