# Generated by Django 5.1.3 on 2024-12-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0003_alter_tguser_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tguser',
            managers=[
            ],
        ),
    ]
